name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: andymckay/pycodestyle-action@0.1.3
      - uses: psf/black@stable
        with:
          black_args: ". --check --line-length 79"
